// Generated by CoffeeScript 1.10.0
(function() {
  var coffee, gulp;

  gulp = require('gulp');

  coffee = require('gulp-coffee');

  gulp.task('coffee', function() {
    return gulp.src('coffee/*.coffee').pipe(coffee()).pipe(gulp.dest('public/js'));
  });

  gulp.task('watch', function() {
    return gulp.watch('coffee/*.coffee', ['coffee']);
  });

  gulp.task('default', ['coffee', 'watch']);

}).call(this);
